import { Hypergraph } from "./priority-traversal-types";

export const stackedBarChartHypergraph: Hypergraph = {
  "0": {
    id: "0",
    displayName: "Stacked Bar Chart",
    description: "Major Trophies for some English teams. Axes team and sum trophies.",
    parents: [],
    children: ["1", "2", "22"],
    priority: 0,
  },
  "1": {
    id: "1",
    displayName: "X-axis",
    description: "Contains 4 teams.",
    parents: ["0"],
    children: ["3", "4", "5", "6"],
    priority: 1,
  },
  "2": {
    id: "2",
    displayName: "Legend",
    description: "Contains 3 contests.",
    parents: ["0"],
    children: ["7", "8", "9"],
    priority: 2,
  },
  "3": {
    id: "3",
    displayName: "Arsenal",
    description: "17 trophies. Contains 3 contests. Bar representing trophies won by Arsenal.",
    parents: ["1"],
    children: ["10", "11", "12"],
    priority: 2,
  },
  "4": {
    id: "4",
    displayName: "Chelsea",
    description: "15 trophies. Contains 3 contests. Bar representing trophies won by Chelsea.",
    parents: ["1"],
    children: ["13", "14", "15"],
    priority: 2,
  },
  "5": {
    id: "5",
    displayName: "Liverpool",
    description: "15 trophies. Contains 3 contests. Bar representing trophies won by Liverpool",
    parents: ["1"],
    children: ["16", "17", "18"],
    priority: 2,
  },
  "6": {
    id: "6",
    displayName: "Manchester United",
    description: "28 trophies. Contains 3 contests. Bar representing trophies won by Manchester United.",
    parents: ["1"],
    children: ["19", "20", "21"],
    priority: 2,
  },
  "7": {
    id: "7",
    displayName: "BPL",
    description: "22 trophies. Contains 4 teams. Legend grouping for the BPL competition.",
    parents: ["2"],
    children: ["10", "13", "16", "19"],
    priority: 3,
  },
  "8": {
    id: "8",
    displayName: "FA Cup",
    description: "42 trophies. Contains 4 teams. Legend grouping for the FA Cup competition.",
    parents: ["2"],
    children: ["11", "14", "17", "20"],
    priority: 3,
  },
  "9": {
    id: "9",
    displayName: "CL",
    description: "11 trophies. Contains 4 teams. Legend grouping for the CL competition.",
    parents: ["2"],
    children: ["12", "15", "18", "21"],
    priority: 3,
  },
  "10": {
    id: "10",
    displayName: "Arsenal BPL",
    description: "3 trophies.",
    parents: ["3", "7"],
    children: [],
    priority: 4,
  },
  "11": {
    id: "11",
    displayName: "Arsenal FA Cup",
    description: "14 trophies.",
    parents: ["3", "8"],
    children: [],
    priority: 4,
  },
  "12": {
    id: "12",
    displayName: "Arsenal CL",
    description: "0 trophies.",
    parents: ["3", "9"],
    children: [],
    priority: 4,
  },
  "13": {
    id: "13",
    displayName: "Chelsea BPL",
    description: "5 trophies.",
    parents: ["4", "7"],
    children: [],
    priority: 4,
  },
  "14": {
    id: "14",
    displayName: "Chelsea FA Cup",
    description: "8 trophies.",
    parents: ["4", "8"],
    children: [],
    priority: 4,
  },
  "15": {
    id: "15",
    displayName: "Chelsea CL",
    description: "2 trophies.",
    parents: ["4", "9"],
    children: [],
    priority: 4,
  },
  "16": {
    id: "16",
    displayName: "Liverpool BPL",
    description: "1 trophy.",
    parents: ["5", "7"],
    children: [],
    priority: 4,
  },
  "17": {
    id: "17",
    displayName: "Liverpool FA Cup",
    description: "8 trophies.",
    parents: ["5", "8"],
    children: [],
    priority: 4,
  },
  "18": {
    id: "18",
    displayName: "Liverpool CL",
    description: "6 trophies.",
    parents: ["5", "9"],
    children: [],
    priority: 4,
  },
  "19": {
    id: "19",
    displayName: "Manchester BPL",
    description: "13 trophies.",
    parents: ["6", "7"],
    children: [],
    priority: 4,
  },
  "20": {
    id: "20",
    displayName: "Manchester FA Cup",
    description: "12 trophies.",
    parents: ["6", "8"],
    children: [],
    priority: 4,
  },
  "21": {
    id: "21",
    displayName: "Manchester United CL",
    description: "3 trophies.",
    parents: ["6", "9"],
    children: [],
    priority: 4,
  },
  "22": {
    id: "22",
    displayName: "Y-axis",
    description: "Count of trophies. Values range from 0 to 30 on a numerical scale.",
    parents: ["0"],
    children: [],
    priority: 2,
  },
};
