import { Hypergraph } from "./priority-traversal-types";

export const lineGraphHypergraph: Hypergraph = {
  "0": {
    id: "0",
    displayName: "Line Graph",
    description:
      "Monthly Average Temperature for Chicago and Seattle in Summer. With axes month and temperature in Fahrenheit.",
    parents: [],
    children: ["1", "2"],
    priority: 0,
  },
  "1": {
    id: "1",
    displayName: "X-axis",
    description: "Contains 3 months.",
    parents: ["0"],
    children: ["8", "9", "10"],
    priority: 1,
  },
  "2": {
    id: "2",
    displayName: "Legend",
    description: "Contains 2 cities.",
    parents: ["0"],
    children: ["15", "16"],
    priority: 2,
  },
  "8": {
    id: "8",
    displayName: "June",
    description: "Contains 2 points.",
    parents: ["1"],
    children: ["27", "28"],
    priority: 3,
  },
  "9": {
    id: "9",
    displayName: "July",
    description: "Contains 2 points.",
    parents: ["1"],
    children: ["29", "30"],
    priority: 3,
  },
  "10": {
    id: "10",
    displayName: "August",
    description: "Contains 2 points.",
    parents: ["1"],
    children: ["31", "32"],
    priority: 3,
  },
  "15": {
    id: "15",
    displayName: "Chicago",
    description: "Contains 3 points.",
    parents: ["2"],
    children: ["27", "29", "31"],
    priority: 3,
  },
  "16": {
    id: "16",
    displayName: "Seattle",
    description: "Contains 3 points.",
    parents: ["2"],
    children: ["28", "30", "32"],
    priority: 3,
  },
  "27": {
    id: "27",
    displayName: "Chicago in June",
    description: "70.4 Fahrenheit. Data point.",
    parents: ["8", "15"],
    children: [],
    priority: 4,
  },
  "28": {
    id: "28",
    displayName: "Seattle in June",
    description: "68.0 Fahrenheit. Data point.",
    parents: ["8", "16"],
    children: [],
    priority: 4,
  },
  "29": {
    id: "29",
    displayName: "Chicago in July",
    description: "72.7 Fahrenheit. Data point.",
    parents: ["9", "15"],
    children: [],
    priority: 4,
  },
  "30": {
    id: "30",
    displayName: "Seattle in July",
    description: "69.5 Fahrenheit. Data point.",
    parents: ["9", "16"],
    children: [],
    priority: 4,
  },
  "31": {
    id: "31",
    displayName: "Chicago in August",
    description: "75.7 Fahrenheit. Data point.",
    parents: ["10", "15"],
    children: [],
    priority: 4,
  },
  "32": {
    id: "32",
    displayName: "Seattle in August",
    description: "69.4 Fahrenheit. Data point.",
    parents: ["10", "16"],
    children: [],
    priority: 4,
  },
};
